[project]
name = "runpod-real-esrgan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=12.1.1",
    "requests>=2.32.5",
    "runpod>=1.8.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
